version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  website:
    stdin_open: true
    tty: true
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
        - '.:/chatbot'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box:

